import random
Quotes_list=[
'Learning to listen is the essence of intelligent living. @SadhguruJV #SadhguruQuotes',
'Confidence and stupidity are a very dangerous combination, but they generally go together. @SadhguruJV #SadhguruQuotes',
'Death is a fiction created by people who live their lives in total unawareness. There is only life, life and life alone, moving from one dimension to another, another dimension to another. @SadhguruJV #SadhguruQuotes',
'When you have that, you dream of this and when you have this, you dream of that. Maybe you call it romantic, but it’s just plain stupidity. It destroys life. @SadhguruJV #SadhguruQuotes',
'It is our compulsive reaction to the situations in which we are placed that causes stress. @SadhguruJV #SadhguruQuotes',
'The only thing that stands between you and your well-being is a simple fact: you have allowed your thoughts and emotions to take instruction from the outside rather than the inside.@SadhguruJV #SadhguruQuotes',
'To rise above the modifications of your mind, when you cease your mind, when you cease to be a part of your mind, that is yoga. @SadhguruJV #SadhguruQuotes',
'Your life is just about craving, and making something else tremendously more important than you. @SadhguruJV #SadhguruQuotes',
'To program the calories you must consume and the number of hours you must sleep is a foolish way to handle life. @SadhguruJV #SadhguruQuotes',
'Confusion is a good state to be in. It means you are looking, constantly looking.  @SadhguruJV #SadhguruQuotes',
'The man who does only as much as is needed will only get that much. @SadhguruJV #SadhguruQuotes',
'Generally, the smartest people on the planet – those people who think they are really smart – tend to have the most horrible relationships. @SadhguruJV #SadhguruQuotes',
'Yogis are not against pleasure. It is just that they are unwilling to settle for little pleasures. They are greedy. @SadhguruJV #SadhguruQuotes',
'Money is definitely needed, but how much money do we really need? If we would change our idea of a successful life to a joyful life, we would find our need for money would dramatically decrease. @SadhguruJV #SadhguruQuotes',
'The way you eat not only decides your physical health, but the very way you think, feel, and experience life. Trying to eat intelligently means understanding what kind of fuel this body is designed for and accordingly supplying it, so that it functions at its best. @SadhguruJV #SadhguruQuotes',
'To be enlightened is not a condition of certainty. It is to move from limited knowing to boundless unknowing, from gravitas to grace. @SadhguruJV #SadhguruQuotes',
'The most incredible thing is that you can know everything you wish to know with your eyes closed. @SadhguruJV #SadhguruQuotes',
'Most carnivorous animals do not eat every day—definitely not three times a day! They know the food they eat moves very slowly through their tracts. @SadhguruJV #SadhguruQuotes',
'Mysticism is like pure science; it has no use. Mysticism is just the human longing to know… Occult is not science. Occult is just technology. @SadhguruJV #SadhguruQuotes',
'You cannot choose a Guru. Deepen your longing and the Guru will choose you. @SadhguruJV #SadhguruQuotes',
'Only if you know to what extent your logic should go and where it should not go, your life will be beautiful. @SadhguruJV #SadhguruQuotes',
'One should use information and logic as a drunkard would use a lamp post, only for support, not for illumination. @SadhguruJV #SadhguruQuotes',
'Your body is on loan from the planet. All the countless numbers of people who have lived on this planet before you and me have all become topsoil, and so will you. This planet will collect back atom by atom what it has loaned to you. @SadhguruJV #SadhguruQuotes',
'Responsibility simply means your ability to respond. @SadhguruJV #SadhguruQuotes',
'There is only one calamity: ignorance. And there is only one solution: enlightenment. @SadhguruJV #SadhguruQuotes',
'Unless you do the right things, the right things will not happen to you. @SadhguruJV #SadhguruQuotes',
'But when it comes to the inner situation, there is only one ingredient: you. At least you must happen the way you want. @SadhguruJV #SadhguruQuotes',
'If you handle your entire life with logic alone, you will end up a mess. @SadhguruJV #SadhguruQuotes',
'Why do we refer to the mind as a circus? A circus is not a mess; a circus is a very coordinated activity deliberately made to look like a mess. On one level it is a mess, but on another, it is a highly coordinated activity.@SadhguruJV #SadhguruQuotes',
'Your ideas of good and bad are just a certain level of prejudice against life. @SadhguruJV #SadhguruQuotes',
'Man needs entertainment simply to hide his madness. If he was perfectly sane, he would not need entertainment. He could just sit and watch this bamboo grow. He does not really need entertainment. @SadhguruJV #SadhguruQuotes',
'Whatever has been the highest experience in your life should become the centerpiece around which your life is structured. @SadhguruJV #SadhguruQuotes',
'An intellectual understanding that is not backed by experiential knowledge can lead to mind games and deceptive states. @SadhguruJV #SadhguruQuotes',
'Renunciation, or refusing to identify with that which one gathers (however precious it may be), is the ultimate doorway to knowing. @SadhguruJV #SadhguruQuotes',
'If you want God as a tranquilizer, it is okay as an idea, but if you want the Divine to be an awakening process in your life, an idea is not good enough. @SadhguruJV #SadhguruQuotes',
'They have been promising us for a long time — in every culture — that they are going to take us to heaven. They promise heaven because they are making a hell out of this place. @SadhguruJV #SadhguruQuotes',
'The path is not difficult. It is very simple. If you are simple, it’s very simple. If you are all wound up, the path is very, very winding. That’s all it is. @SadhguruJV #SadhguruQuotes',
'I learned to create a little more space between my thoughts and actions—actually between my feelings and reactions. This is extremely important; without it, life can be a real roller coaster ride. @SadhguruJV #SadhguruQuotes',
'By consciously getting your body into a certain posture, you can also elevate your consciousness, you can change the very way you feel, think, understand, and experience life simply by sitting in a particular way. @SadhguruJV #SadhguruQuotes',
'Life is a circus when your intellect and your body alone are involved. Life is a dance, when the intelligence begins to play its role @SadhguruJV #SadhguruQuotes',
'Enlightenment is not an attainment or an achievement. It is a homecoming. @SadhguruJV #SadhguruQuotes',
'The identity around which the intellect functions is called ahankara. @SadhguruJV #SadhguruQuotes',
'Sunlight comes into your house not because you want it. It happens because you open the windows. @SadhguruJV #SadhguruQuotes',
'Your mind need not be controlled; your mind needs to be liberated. @SadhguruJV #SadhguruQuotes',
'Things do not descend upon anything that is not ready to receive them @SadhguruJV #SadhguruQuotes',
'This is because the way of the physical is circumscribed. The body has only so much of a role to play in your life. If you try to stretch it to all of your life, you will suffer because you are trying to create a falsehood. @SadhguruJV #SadhguruQuotes',
'The spiritual journey is a journey towards clarity, but never towards certainty. When you draw conclusions about beginnings and endings, you are a believer. When you accept that you really do not know anything, you become a seeker. @SadhguruJV #SadhguruQuotes',
'Eating natural foods, in their uncooked condition, when the cells are still alive, will bring an enormous sense of health and vitality to the system. @SadhguruJV #SadhguruQuotes',
'When everything you do is a success, you tend to start believing that the planets revolve around you, not the sun! @SadhguruJV #SadhguruQuotes',
'Literally, yoga means “union.” When you are in yoga, it means that in your experience, everything has become one. This is the essence of the science. This is also its deepest aim.@SadhguruJV #SadhguruQuotes',
'So the whole process of spirituality is just about enhancing your perception. @SadhguruJV #SadhguruQuotes',
'Life has no use at all, declared Adiyogi. It is simply a phenomenon. Little acts have purpose. But life is not framed within the narrow grid of utility. It is beyond frames. It is beyond grids. It is beyond utility. If you have a taste of this existence beyond purpose, of life beyond sense, you are enlightened. @SadhguruJV #SadhguruQuotes',
'There is a Force within That gives you life Seek that. —Rumi',
'Unless you begin to see the hollowness of where you are right now, you will not begin to seek something else strongly. @SadhguruJV #SadhguruQuotes',
'The essence of yoga, as we have said before, is just this—to arrive at that moment where there is a clear space between you and your mind. @SadhguruJV #SadhguruQuotes',
'Reactivity is enslavement. Responsibility is freedom. @SadhguruJV #SadhguruQuotes',
'Fundamentally, the basis of yoga is just this: to initiate a process of self-creation where the nature of your body, your emotion, your mind, your energy is consciously created by you. @SadhguruJV #SadhguruQuotes',
'being on the spiritual path is not about making life pleasant. It’s about seeing how to transcend both the pleasant and the unpleasant. @SadhguruJV #SadhguruQuotes',
'Once you have come with the human form, life has given you a certain sense of intelligence, a certain sense of awareness and freedom to choose what you want to be right now, in this moment. @SadhguruJV #SadhguruQuotes',
'If you try to make the limited unlimited, you will suffer. @SadhguruJV #SadhguruQuotes',
'Right now, you don’t have the necessary faculties to know anything which is beyond the physical. If you recognize this, if you understand this, if you accept this absolutely, only then the other dimension opens up. @SadhguruJV #SadhguruQuotes',
'Until we learn to respect our women, until every man learns to respect a woman, he will never know himself; there is no way, because half of him is just that. @SadhguruJV #SadhguruQuotes',
'Fruit is the most easily digestible food and all human beings know this instinctively. @SadhguruJV #SadhguruQuotes',
'If you tell yourself you don’t want to think a certain thought, that is precisely the first thing your mind will produce! That is the nature of the human mind. @SadhguruJV #SadhguruQuotes',
'Life should touch you, even if life smothers you, it\'s better than remaining untouched by life @SadhguruJV #SadhguruQuotes',
'All we can ever experience happens from within us. @SadhguruJV #SadhguruQuotes',
'If you consciously get your body into different postures, you can elevate your consciousness. @SadhguruJV #SadhguruQuotes',
'Freedom—or mukti or moksha—is seen as the natural longing in every human being and our ultimate destination. @SadhguruJV #SadhguruQuotes',
'The entire aim and endeavor of yoga is to open up the cocoon of the physical body to the larger sensory body where you experience everything as a part of you. @SadhguruJV #SadhguruQuotes',
'To be human means you can mold situations you are living in the way you want them. @SadhguruJV #SadhguruQuotes',
'It does not matter how large a boundary we set, the moment you become conscious of it, the longing to break it is instinctive. @SadhguruJV #SadhguruQuotes',
'The logical aspect of your life and the experiential dimension of your life are diametrically opposite to each other. @SadhguruJV #SadhguruQuotes',
'Creator is just pure intelligence. Intelligence beyond logic is Creator, or what you are referring to as God. @SadhguruJV #SadhguruQuotes',
'That which knows how to bend will not break. @SadhguruJV #SadhguruQuotes',
'The only thing that stands between you and your well-being is a simple fact: you have allowed your thoughts and emotions to take instruction from the outside rather than the inside. @SadhguruJV #SadhguruQuotes',
'True human capabilities will not find expression in competition. True human capabilities will find expression only in absolute relaxation. Your mind, your body will work best, will find fullest expression, only when you are joyful and peaceful, and quiet within yourself. @SadhguruJV #SadhguruQuotes',
'Bullshit may get you to the top, but it never lets you stay there! @SadhguruJV #SadhguruQuotes',
'What you accumulate can be yours, but it can never be you. @SadhguruJV #SadhguruQuotes',
'The whole spiritual process is just this: that you are willing to take the next step not knowing where it will lead you. If you are not ready for that, that means you are not ready for any new possibility. @SadhguruJV #SadhguruQuotes',
'I am not here to speak the Truth. I am here just to give you a method to perceive it. @SadhguruJV #SadhguruQuotes',
'A human is not a being; he is a becoming. He is an ongoing process, nothing is fixed. @SadhguruJV #SadhguruQuotes',
'The whole world itself is going through a unique kind of neurosis, which was not there in the past. This is simply because modern man has stopped using his body to a large extent. @SadhguruJV #SadhguruQuotes',
'The very essence of dhyana, or meditativeness, is that you push yourself to the highest possible intensity where, after some time, there is no effort.  @SadhguruJV #SadhguruQuotes',
'One should use information and logic as a drunkard would use a lamp post – only for support, not for illumination. @SadhguruJV #SadhguruQuotes',
'Learning is a natural human trait. When you learn something that you did not know, it should make you joyful. But if learning is making children miserable, then we have not understood how to impart learning. @SadhguruJV #SadhguruQuotes',
'Most people are investing their whole lifetime just for their material well-being. Dying to live, this is called @SadhguruJV #SadhguruQuotes',
'When we utter the word ‘spirituality’, what we are saying is, “I want to become all-inclusive, or all-exclusive. I want to include everything as a part of myself, or I want to just exclude everything, including myself. @SadhguruJV #SadhguruQuotes',
'There is a certain space within you which never gets disturbed, which is never in any kind of turmoil; a space which cannot be touched by outside situations. @SadhguruJV #SadhguruQuotes',
'Every human being is longing for involvement. Not for touch, not for a kiss, not for sex, not for anything else; one is basically longing for a deep sense of involvement. @SadhguruJV #SadhguruQuotes',
'in the inner life, there is only one kind of revolution and it is a silent one. It is about moving from unwillingness to willingness. @SadhguruJV #SadhguruQuotes',
'No boundary, no burden. This is the turnaround in human consciousness that needs to take place. Once this happens, it is not that the cosmos begins to happen your way. Instead, what you are becomes cosmic. This is not transcendence; this is homecoming. @SadhguruJV #SadhguruQuotes',
'What does it mean to become a Buddha? “Bu” means “Buddhi,” the intellect. One who is above his intellect is a Buddha. @SadhguruJV #SadhguruQuotes',
'The whole art of being a Guru is just this: to constantly puncture people’s egos and still manage to remain their friend. @SadhguruJV #SadhguruQuotes',
'The Whole process of spirituality is just about enhancing your perception. @SadhguruJV #SadhguruQuotes',
'What people are suffering is their freedom. That\'s why it is so tragic. @SadhguruJV #SadhguruQuotes',
'human being who has transcended his intellect, the discriminatory and logical dimensions of his life, is a Buddha. @SadhguruJV #SadhguruQuotes',
'Every opinion you have about anything can be a limiting identity @SadhguruJV #SadhguruQuotes',
'Once your intellect gets identified with something, it gets chained to the identifications, and leaves you with a completely distorted experience of the world. @SadhguruJV #SadhguruQuotes',
'The walls of self-preservation that you build for today are the walls of self-imprisonment for tomorrow. Boundaries that you establish in your life as a protection for yourself today will feel like constraints tomorrow. @SadhguruJV #SadhguruQuotes',
'Someone is not stressful because of what he is doing; someone is stressful because he doesn\'t know how to manage his own inner system. It is not the nature of the job which makes one stressful. @SadhguruJV #SadhguruQuotes',
'If you are forming relationships to seek happiness – you trying to squeeze happiness out of someone and that person trying to squeeze happiness out of you – this is going to be a painful relationship after some time. @SadhguruJV #SadhguruQuotes',
'If you employ your intelligence and make an attempt to reach your ultimate nature, this is called gnana yoga, or the yoga of knowing. @SadhguruJV #SadhguruQuotes',
'Today people just go on working, working and working. Not because they are creating something fantastic, but simply because they have to work, otherwise they don’t know what to do with themselves. @SadhguruJV #SadhguruQuotes',
'Morality always differs from person to person, according to time, place, situation—and convenience. @SadhguruJV #SadhguruQuotes',
'Relief from something that you cannot hold within you is always the greatest pleasure, isn’t it? Whatever that thing may be! @SadhguruJV #SadhguruQuotes',
'Believing means you have assumed something that you do not know; seeking means you have realized that you do not know. @SadhguruJV #SadhguruQuotes',
'The science of yoga is, quite simply, the science of being in perfect alignment, in absolute harmony, in complete sync with existence.  @SadhguruJV #SadhguruQuotes',
'The modern societies are encouraging exclusiveness. Exclusiveness will naturally lead to depression. People are depressed like never before on this planet. @SadhguruJV #SadhguruQuotes',
'In the process of creating what we want, in pursuit of our happiness, we are just destroying the very source of our life, this planet; we are making a bonfire out of it. But still we are not satisfied, nor are we any more joyful than what people were five hundred years ago. @SadhguruJV #SadhguruQuotes',
'Belief is just like morality. People who believe something often think they are superior to others. @SadhguruJV #SadhguruQuotes',
'Intuition is not a different dimension of perception, as people usually try to make out. Intuition is just a quicker way of arriving at the same answer. Intuition is just a way of making use of the data and jumping the steps @SadhguruJV #SadhguruQuotes',
'Yoga is fundamentally aimed at enhancing your experience beyond the five senses. @SadhguruJV #SadhguruQuotes',
'Now the need for seeking something outside will completely disappear. Once you are blissful by your own nature, your life becomes an expression of your blissfulness, not a pursuit of happiness. @SadhguruJV #SadhguruQuotes',
'“Modern science tells us that all of existence is just energy manifesting itself in different ways and in different forms. @SadhguruJV #SadhguruQuotes',
'The yogic culture is not god-oriented – and this is what makes it an invaluable contribution to a world ravaged by wildly conflicting definitions of the divine. @SadhguruJV #SadhguruQuotes',
'Now, every child does have the necessary intelligence. You create an atmosphere for him to grow into his intelligence rather than superimposing your rottenness on him. @SadhguruJV #SadhguruQuotes',
'There one exists not as an accumulation of memory and experience, not as an embodiment of love or compassion. There one simply exists in an intensity of inclusiveness. @SadhguruJV #SadhguruQuotes',
'you look at your child with intelligence, do you see that to get him everything that he asks for is sheer stupidity? @SadhguruJV #SadhguruQuotes',
'Why human life needs so much attention is because we are human beings. @SadhguruJV #SadhguruQuotes',
'The logic is simple: if you do the right things, the right things will happen to you even without your intent.@SadhguruJV #SadhguruQuotes',
'Don’t think of this as your first step or last step. Just be here as a piece of life. That is the best way to be. You are not a young man; you are not an old man. You are just a piece of life. @SadhguruJV #SadhguruQuotes',
'What the mind forgets is that the ability to respond is the basis of life. If the ability is acknowledged willingly, you become blissful. If it happens unwillingly, you become miserable. @SadhguruJV #SadhguruQuotes',
'This moment, the quality of your life is simply decided by how peaceful and joyous you are right now within yourself. That is all that decides the quality of your life. @SadhguruJV #SadhguruQuotes',
'Without knowing the essential nature of this (referring to the self), we are trying to make a life outside. That is the biggest mistake humanity has made. @SadhguruJV #SadhguruQuotes',
'The self is the same. Either you wear a masculine peel or a feminine peel. That is all it is. @SadhguruJV #SadhguruQuotes',
'true intelligence is just life and life—and that which is the source of life. @SadhguruJV #SadhguruQuotes',
'Peace and joy are the basic requirements for a life of well-being. @SadhguruJV #SadhguruQuotes',
'Peace and joy are not things you attain at the end of life. They are the basis of your life. @SadhguruJV #SadhguruQuotes',
'There is no such thing as death. There is only life, life, and life alone - moving from one dimension to another. @SadhguruJV #SadhguruQuotes',
'Fundamentally management is your ability to inspire people to do their best and that is all you can do. If everybody around you is doing his best, that is the best possible management that can happen. @SadhguruJV #SadhguruQuotes',
'For a human being, life doesn’t seem to end with survival; life begins with survival.@SadhguruJV #SadhguruQuotes',
'What then is the way out? The way out is a very simple change in direction. You just need to see that the source and basis of your experience is within you. @SadhguruJV #SadhguruQuotes',
'An idiot is incapable of drawing conclusions. A mystic is unwilling to draw conclusions. The rest have glorified their conclusions as knowledge.@SadhguruJV #SadhguruQuotes',
'Every thought that arises in the mind has its roots in data you have already accumulated. @SadhguruJV #SadhguruQuotes',
'The smartest thing about most people is their phone. @SadhguruJV #SadhguruQuotes',
'The first thing is to stand up and be sensible. To handle this body, to handle this mind, to handle these emotions, things that are within you right now, to handle them sensibly. @SadhguruJV #SadhguruQuotes',
'I do not know” is the doorway—the only doorway—to seeking and knowing. @SadhguruJV #SadhguruQuotes',
'your success in the world depends essentially on how well you harness the prowess of the body and mind. So, in order to achieve success, pleasantness has to be the fundamental quality within you. @SadhguruJV #SadhguruQuotes',
'The ability to simply look without motive is missing in the world today @SadhguruJV #SadhguruQuotes',
'Human perception through the sense organs is always piecemeal. It can give you an illusion of completeness but can never comprehend the whole. @SadhguruJV #SadhguruQuotes',
'Discern the real from the illusory, what is existentially true from what is psychologically true. @SadhguruJV #SadhguruQuotes',
'What kind of food you eat, how much you eat, how you eat, turning it from a compulsive pattern into a conscious process: this is the essence of fasting.  @SadhguruJV #SadhguruQuotes',
'We are the most comfortable generation to have ever lived on this planet. The rub is that we are definitely not the most joyful, or the most loving, or the most peaceful. @SadhguruJV #SadhguruQuotes',
'God loves you’ is not significant. If you are in such a way that everybody around you cannot help but fall in love with you – now, that is great! @SadhguruJV #SadhguruQuotes',
'Inner pleasantness is a surefire insurance for the making of a peaceful society and a joyful world. @SadhguruJV #SadhguruQuotes',
'technology will only bring comfort and convenience to us, not well-being.  @SadhguruJV #SadhguruQuotes #texhnology',
'Even if the world doesn’t happen the way you want it, at least your thoughts and emotions should happen the way you want them to. @SadhguruJV #SadhguruQuotes',
'unless we do the right things, the right things will not happen to us: this is true not just of the outside world, but also the inside. @SadhguruJV #SadhguruQuotes',
'Choices that you make out of inability are not life solutions. @SadhguruJV #SadhguruQuotes',
'In fact, every kind of pleasantness that we experience—whether peace or joy or ecstasy—is a kind of chemistry. The yogic system has always known this. @SadhguruJV #SadhguruQuotes',
'All human experience is one hundred percent self-created.@SadhguruJV #SadhguruQuotes',
'Seeking is not about looking for something. It is about enhancing your perception, your very faculty of seeing. @SadhguruJV #SadhguruQuotes',
'Your ideas of good and bad are just a certain level of prejudice against life @SadhguruJV #SadhguruQuotes',
'You are struggling with the walls of resistance that you have built around yourself. @SadhguruJV #SadhguruQuotes',
'The thing to remember is that none of these will settle you in any enduring way. Human life is longing for unlimited expansion, and that is the only thing that will settle you for good. @SadhguruJV #SadhguruQuotes',
'responsibility is not a teaching in civics. It is the simplest and easiest way for you to express your own divinity @SadhguruJV #SadhguruQuotes',
'Any fool will seek liberation when he is suffering. It takes enormous intelligence to seek liberation when everything is going well.@SadhguruJV #SadhguruQuotes',
'If you generate a powerful thought and let it out, it will always manifest itself. For this to happen, it is important that you do not impede and weaken your thought by creating negative and self-defeating thought patterns. @SadhguruJV #SadhguruQuotes',
'Shiva does not spell religion. Shiva spells responsibility – our ability to take our very life process in our hands. for @SadhguruJV #SadhguruQuotes',
'it is singularly unpleasant—for you and for those at the receiving end. It is also counterproductive and therefore inefficient. @SadhguruJV #SadhguruQuotes',
'When people feel insecure they want to drink and sleep, because sleep is just a small manifestation of death. @SadhguruJV #SadhguruQuotes',
'Maybe it is beyond your perception right now, but because your physical form is just a fragment of the planet, everything that is happening to any part of the universe is also in some way happening to you! @SadhguruJV #SadhguruQuotes',
'just watch whether you are for the Creator or against the Creator, every moment in your life. If you see this, everything will be settled. If you can’t think of your Creator @SadhguruJV #SadhguruQuotes',
'Compassion is definitely a more liberating emotion than love. @SadhguruJV #SadhguruQuotes',
'But to be loving is simply this: a willingness to respond freely and openly. @SadhguruJV #SadhguruQuotes',
'Love is not something you do; it is just the way you are. @SadhguruJV #SadhguruQuotes',
'For me, Shambho is not just a word. It is all that I know. It is all that flows through me. It is the last thing I will utter before I shed my body. It is the password to my very existence. #shambho @SadhguruJV #SadhguruQuotes',
'Love has nothing to do with someone else. It is all about you. It is a way of being. It essentially means you have brought sweetness into your emotion. @SadhguruJV #SadhguruQuotes',
'Love has nothing to do with someone else. It is all about you. It is a way of being. It essentially means you have brought sweetness into your emotion. @SadhguruJV #SadhguruQuotes',
'Blissfulness means life is happening in an exuberant manner, and that is all that life seeks. @SadhguruJV #SadhguruQuotes',
'the ability to respond is the basis of life. @SadhguruJV #SadhguruQuotes',
'If you can joyfully do whatever is needed in a given situation, this is freedom @SadhguruJV #SadhguruQuotes',
'If your humanity overflows, divinity will follow and serve you. It has no other choice. @SadhguruJV #SadhguruQuotes',
'Karma can be compared to a seed. Before the rains, the whole land is barren. There would be nothing. It rains; suddenly all kinds of vegetation will sprout up. The seeds are already there; they’re just waiting for the right kind of atmosphere @SadhguruJV #SadhguruQuotes',
'When you were just born, it did not take immediate effect. It was waiting. As the process of growth happens, it looks for the right kind of situation and takes effect. @SadhguruJV #SadhguruQuotes',
'The foundations of peace and bliss are not about attending to the external realities of your life, but in accessing and organizing the inner nature of your being.  @SadhguruJV #SadhguruQuotes',
'it is your identity that manages and determines your intellect. @SadhguruJV #SadhguruQuotes',
'We transform the physical body from a series of compulsions of flesh, blood, and hormones into a conscious process, a powerful instrument of perception and knowing. @SadhguruJV #SadhguruQuotes',
'If you are willing, every moment of your life can be a fantastic experience. Just the act of inhaling and exhaling can be a tremendous love affair. @SadhguruJV #SadhguruQuotes',
'Our lives become beautiful not because we are perfect. Our lives become beautiful because we put our heart into what we are doing. @SadhguruJV #SadhguruQuotes',
'By just watching the sunset I become blissful, is that true bliss? When I am saying my prayers if I become blissful, is that true bliss? When I am meditating and have become blissful, is that true bliss?” How you become blissful, it doesn’t matter. Somehow you become blissful. That is all that matters. @SadhguruJV #SadhguruQuotes',
'When you are constantly in pursuit of security, you are in pursuit of death, because life is never secure. It doesn’t matter what you do @SadhguruJV #SadhguruQuotes',
'If you manage a situation, not just things happening there, people should feel elevated just being in that space. Above all, you must feel wonderful being there. @SadhguruJV #SadhguruQuotes',
'When it comes to action, capability could play a role. But when it comes to response, it is just a question of willingness. @SadhguruJV #SadhguruQuotes',
'What we need is not good human beings; we need sensible human beings. @SadhguruJV #SadhguruQuotes',
'It’s considered totally obscene to make any request to God, because if he doesn’t know, what’s the point asking him? @SadhguruJV #SadhguruQuotes',
'You will become spiritual only when the realm of your experience transcends the physical reality, and you begin experiencing that which is not physical.@SadhguruJV #SadhguruQuotes',
'Incredible things can be done simply because we are committed that we want it to happen, that\'s all.@SadhguruJV #SadhguruQuotes',
'Shi-va is the centripetal force that holds existence together; Shakti is the centrifugal force that gives rise to the explosive diversity of existence. @SadhguruJV #SadhguruQuotes',
'The moment you get strongly identified, you lose your perspective on life! @SadhguruJV #SadhguruQuotes',
'This is the fundamental question about life. How do you want to spend this moment? @SadhguruJV #SadhguruQuotes',
'Whatever is in your hands, you keep that in perfect condition; then what is beyond you will anyway happen. But people are always trying to work at what is beyond them, not taking care of what is in their hands. @SadhguruJV #SadhguruQuotes',
'If you are really interested in knowing life in all its depth and dimension, it is imperative that you look inward, not out. @SadhguruJV #SadhguruQuotes',
'Dhyana or meditation, means to be beyond the limitations of your body and mind. @SadhguruJV #SadhguruQuotes',
'Love’s secret is always lifting its head out from under the covers, “Here I am!” ~Rumi #rumiquotes ',
'Be empty of worrying.... Why do you stay in prison when the door is so wide open? Move outside the tangle of fear-thinking. ~Rumi #rumiquotes',
'Wear gratitude like a cloak and it will feed every corner of your life. ~Rumi #rumiquotes',
'Hear blessings dropping their blossoms around you. ~Rumi #rumiquotes',
'Lovers don’t finally meet somewhere. They’re in each other all along. ~Rumi #rumiquotes',
'Be melting snow. Wash yourself of yourself. ~Rumi #rumiquotes',
'God turns you from one feeling to another and teaches by means of opposites, so that you will have two wings to fly, not one. ~Rumi #rumiquotes',
'Do not grieve. Anything you lose comes round in another form. ~Rumi #rumiquotes',
'Sell your cleverness and buy bewilderment... ~Rumi #rumiquotes',
'Why are you so enchanted by this world, when a mine of gold lies within you? ~Rumi #rumiquotes',
'Today, like every other day, we wake up empty and frightened.... Let the beauty we love be what we do. ~Rumi #rumiquotes',
'There are a thousand ways to kneel and kiss the earth. ~Rumi #rumiquotes',
'Why should I stay at the bottom of a well when a strong rope is in my hand? ~Rumi, #rumiquotes',
'A secret freedom opens through a crevice you can barely see. ~Rumi #rumiquotes',
'My head is bursting with the joy of the unknown. My heart is expanding a thousand fold. ~Rumi #rumiquotes',
' As you start to walk out on the way, the way appears. ~Rumi#rumiquotes',
'You were born with wings, why prefer to crawl through life? ~Rumi #rumiquotes',
'Become the sky. Take an axe to the prison wall. Escape. ~Rumi #rumiquotes',
'Lightning, your presence from ground to sky, no one knows what becomes of me, when you take me so quickly. ~Rumi #rumiquotes',
'How can I know anything about the past or the future, when the light of the Beloved shines only Now. ~Rumi #rumiquotes',
'What I most want is to spring out of this personality, then to sit apart from that leaping. I’ve lived too long where I can be reached. ~Rumi #rumiquotes',
'Very little grows on jagged rock. Be ground. Be crumbled, so wildflowers will come up where you are. ~Rumi #rumiquotes',
'Ignorance is God’s prison. Knowing is God’s palace. ~Rumi #rumiquotes',
'This world’s existence is one night long. There’s a great lively gathering that night, but some people sleep through it. ~Rumi #rumiquotes',
'If you are irritated by every rub, how will you be polished? ~Rumi #rumiquotes',
'There is a morning inside you waiting to burst open into Light. ~Rumi #rumiquotes',
'Whosoever knoweth the power of the dance, dwelleth in God. ~Rumi #rumiquotes',
'Out beyond the ideas of wrongdoing and rightdoing, there is a field. I’ll meet you there. ~Rumi #rumiquotes',
'Can you find another market like this? Where, with your one rose, you can buy hundreds of rose gardens? ~Rumi #rumiquotes',
'At night, I open the window and ask the moon to come and press its face against mine. Breathe into me. Close the language-door and open the love-window. The moon won’t use the door, only the window. ~Rumi #rumiquotes',
'The breeze at dawn has secrets to tell you. Don’t go back to sleep. ~Rumi #rumiquotes',
'This is how we are with wine and beautiful food... we want and we get drunk with wanting, then the headache and bitterness afterward. ~Rumi #rumiquotes',
'And don’t think the garden loses its ecstasy in winter. It’s quiet, but the roots are down there riotous. ~Rumi #rumiquotes',
'The core of the seen and unseen universe smiles, but remember smiles come best from those who weep. Lightning, then the rain-laughter. ~Rumi #rumiquotes',
'The way the night knows itself with the moon, be that way with me. Or, alternately translated, Union is a raging river running toward the sea. Tonight the moon kisses the stars. O beloved, be like that to me. ~Rumi #rumiquotes',
'I have lived on the lip of insanity, wanting to know reasons, knocking on a door. It opens. I’ve been knocking from the inside! ~Rumi #rumiquotes',
'In each moment the fire rages, it will burn away a hundred veils. And carry you a thousand steps toward your goal. ~Rumi #rumiquotes',
'Before death takes away what you are given, give away what there is to give. ~Rumi #rumiquotes',
'Now is the time to unite the soul and the world. Now is the time to see the sunlight dancing as one with the shadows. ~Rumi #rumiquotes',
'Birdsong brings relief to my longing. I am just as ecstatic as they are, but with nothing to say. ~Rumi #rumiquotes',
'Isn’t it time to turn your heart into a temple of fire? ~Rumi #rumiquotes',
'Who gets up early to discover the moment light begins? ~Rumi #rumiquotes',
'Your legs will get heavy and tired. Then comes a moment of feeling the wings you’ve grown, lifting. ~Rumi #rumiquotes',
'All day I think about it, then at night I say it. Where did I come from, and what am I supposed to be doing? I have no idea. My soul is from elsewhere, I’m sure of that, and I intend to end up there. ~Rumi #rumiquotes',
'This drunkenness began in some other tavern. When I get back around to that place, I’ll be completely sober. ~Rumi #rumiquotes',
'I cannot stop asking. If I could taste one sip of an answer, I could break out of this prison for drunks. ~Rumi #rumiquotes',
'I am iron resisting the most enormous magnet there is. ~Rumi #rumiquotes',
'Let yourself be silently drawn by the stronger pull of what you really love. ~Rumi #rumiquotes',
'Work in the invisible world at least as hard as you do in the visible. ~Rumi #rumiquotes',
'Take sips of this pure wine being poured. Don’t mind that you’ve been given a dirty cup. ~Rumi #rumiquotes',
'Stop acting so small. You are the universe in ecstatic motion. ~Rumi #rumiquotes',
'There is a way of breathing that’s a shame and a suffocation and there’s another way of expiring, a love breath, that lets you open infinitely. ~Rumi #rumiquotes',
'Keep knocking, and the joy inside will eventually open a window and look out to see who’s there. ~Rumi #rumiquotes',
'The mind, this globe of awareness, is a starry universe that when you push off with your foot, a thousand new roads become clear, as you yourself do at dawn, sailing through the light. ~Rumi #rumiquotes',
'Gamble everything for love, if you’re a true human being. If not, leave this gathering. ~Rumi #rumiquotes',
'Half-heartedness doesn’t reach into majesty. You set out to find God, but then you keep stopping for long periods at mean-spirited roadhouses. ~Rumi #rumiquotes',
'No one knows what makes the soul wake up so happy! Maybe a dawn breeze has blown the veil from the face of God. ~Rumi #rumiquotes',
'Let the waters settle and you will see the moon and the stars mirrored in your own being. ~Rumi #rumiquotes',
'He is a letter to everyone. You open it. It says, Live. ~Rumi #rumiquotes',
'Don’t turn away. Keep your gaze on the bandaged place. That’s where the light enters you. ~Rumi #rumiquotes',
'Love comes with a knife, not some shy question, and not with fears for its reputation! ~Rumi #rumiquotes',
'Love is a madman, working his wild schemes, tearing off his clothes, running through the mountains.... ~Rumi #rumiquotes',
'Come out here where the roses have opened. Let soul and world meet. ~Rumi #rumiquotes',
'Don’t put blankets over the drum! Open completely. Let your spirit ear listen to the green dome’s passionate murmur. ~Rumi #rumiquotes',
'This is how I would die into the love I have for you: as pieces of cloud dissolve in sunlight. ~Rumi #rumiquotes',
'That hurt we embrace becomes joy. Call it to your arms where it can change. ~Rumi #rumiquotes',
'I don’t regret how much I love, and I avoid those who repent their passion. ~Rumi #rumiquotes',' #rumiquotes',
'There is one way of breathing that is shameful and constricted. Then, there’s another way: a breath of love that takes you all the way to infinity. ~Rumi #rumiquotes',
'You must lance an ulcer to heal it. You must tear down parts of an old building to restore it, and so it is with a sensual life that has no spirit in it. ~Rumi #rumiquotes',
'To change, a person must face the dragon of his appetites with another dragon, the life-energy of the soul. ~Rumi #rumiquotes',
'When your love contracts in anger, the atmosphere itself feels threatening. But when you’re expansive, no matter what the weather, you’re in an open, windy field with friends. ~Rumi #rumiquotes',
'Water the fruit trees and don’t water the thorns. ~Rumi #rumiquotes',
'Purify your eyes, and see the pure world. Your life will fill with radiant forms. ~Rumi #rumiquotes',
'How will you know the difficulties of being human, if you’re always flying off to blue perfection? ~Rumi #rumiquotes',
'Where will you plant your grief-seeds? We need ground to scrape and hoe, not the sky of unspecified desire. ~Rumi #rumiquotes',
'If you yearn for holy felicity, shed your arrogance and become a seeker of hearts. ~Rumi #rumiquotes',
'If all you can do is crawl, start crawling. ~Rumi #rumiquotes',' #rumiquotes',
'Sorrows are the rags of old clothes and jackets that serve to cover, and then are taken off. That undressing, and the beautiful naked body underneath, is the sweetness that comes after grief. ~Rumi #rumiquotes',
'Let yourself become living poetry. ~Rumi  #rumiquotes',
'There is a fountain inside you. Don’t walk around with an empty bucket. ~Rumi #rumiquotes',
'Is what I say true? Say yes quickly, if you know, if you’ve known it from before the beginning of the universe. ~Rumi #rumiquotes',
'You are a fountain of the sun’s light. I am a willow shadow on the ground. You make my raggedness silky. ~Rumi #rumiquotes',
'You fill yourself with the sharp pain of love, rather than its fulfillment. ~Rumi #rumiquotes',
'Something opens our wings, something makes boredom and hurt disappear. ~Rumi #rumiquotes',
'Inside of us, there’s a continual autumn. Our leaves fall and are blown out over the water. ~Rumi #rumiquotes',
'If these poems repeat themselves, then so does Spring. ~Rumi #rumiquotes',
'This love is the rose that blooms forever. ~Rumi #rumiquotes',
'Put your thoughts to sleep, do not let them cast a shadow over the moon of your heart. Let go of thinking. ~Rumi #rumiquotes',
'If you want to be more alive, love is the truest health. ~Rumi #rumiquotes',
'And if you are a rose, I am rose-shadow. ~Rumi #rumiquotes',
'I turn all thorn then, but you come back again and make my thorniness fragrant and pink and petaled. ~Rumi #rumiquotes',
'Try another way of looking. Try you looking and the whole universe seeing. ~Rumi #rumiquotes',
'Tonight the moon kisses the stars. ~Rumi #rumiquotes',
'And even if this world burns up hidden harps will still play here. ~Rumi #rumiquotes',
'Even when tied in a thousand knots, the string is still but one. ~Rumi #rumiquotes',
'The garden of love is green without limit and yields many fruit other than sorrow and joy. ~Rumi #rumiquotes',
'Be a lamp, or a lifeboat, or a ladder. Help someone’s soul heal. Walk out of your house like a shepherd. ~Rumi #rumiquotes',
'Dance in the middle of fighting. Dance in your blood. Dance when you’re perfectly free. ~Rumi #rumiquotes',' #rumiquotes',
'Let the lover be disgraceful, crazy, absentminded. Someone sober will worry about events going badly. Let the lover be. ~Rumi #rumiquotes',
'Let lovers be crazy, disgraceful and wild Those who fret about such things Aren’t in love.~Rumi #rumiquotes',
'Only from the heart can you touch the sky. ~Rumi #rumiquotes',
'When you do things from your soul you feel a river moving in you, a joy. When action come from another section, the feeling disappears. ~Rumi #rumiquotes',
'If you could untie your wings and free your soul of jealousy, you and everyone around you would fly up like doves. ~Rumi #rumiquotes',
'I am a drunkard from another kind of tavern. I dance to a silent tune. I am the symphony of stars. ~Rumi #rumiquotes',
'The wound is the place where the Light enters you. ~Rumi #rumiquotes',
'Be occupied, then, with what you really value and let the thief take something else. ~Rumi #rumiquotes',
'I want your sun to reach my raindrops, so your heat can raise my soul upward like a cloud. ~Rumi #rumiquotes',
'Come sit with me! Let us drink the holy wine of happiness. ~Rumi #rumiquotes',
'You go from village to village on your horse asking everyone, “Has anyone seen my horse?” ~Rumi #rumiquotes',
'The ocean of the body crashes against the ocean of the heart. Between them is a barrier they cannot cross. ~Rumi #rumiquotes',
'Burdens are the foundations of ease and bitter things the forerunners of pleasure. ~Rumi #rumiquotes',
'Words are the shadow of reality. If the shadow can be attractive, imagine how much more so can the reality be. #rumiquotes',
'The moment an inspiring thought enters your heart, appreciate it as a dear guest visiting you that day #rumiquotes',
'The world as a whole passes and perishes; you can truly live in each moment. #rumiquotes',
'It is because the seed is concealed in the soil that its secret is revealed by the green orchard #rumiquotes',
'If you love a flower, don’t pick it up. Because if you pick it up it dies and it ceases to be what you love. So if you love a flower, let it be. Love is not about possession. Love is about appreciation.~Osho #oshoquotes',
'Be — don\'t try to become ~Osho #oshoquotes',
'Experience life in all possible ways -- good-bad, bitter-sweet, dark-light, summer-winter. Experience all the dualities. Don\'t be afraid of experience, because the more experience you have, the more mature you become. ~Osho #oshoquotes',
'Friendship is the purest love. It is the highest form of Love where nothing is asked for, no condition, where one simply enjoys giving. ~Osho #oshoquotes',
'Life begins where fear ends ~Osho #oshoquotes',
'Be realistic: Plan for a miracle ~Osho #oshoquotes',
'Drop the idea of becoming someone, because you are already a masterpiece. You cannot be improved. You have only to come to it, to know it, to realize it. ~Osho #oshoquotes',
'Truth is not something outside to be discovered, it is something inside to be realized ~Osho #oshoquotes',
'Creativity is the greatest rebellion in existence. ~Osho #oshoquotes',
'The less people know, the more stubbornly they know it. ~Osho #oshoquotes',
'Courage Is a Love Affair with the Unknown ~Osho #oshoquotes',
'My meditation is simple. It does not require any complex practices. It is simple. It is singing. It is dancing. It is sitting silently ~Osho #oshoquotes',
'Truth is not to be found outside. No teacher, no scripture can give it to you. It is inside you and if you wish to attain it, seek your own company. Be with yourself. ~Osho #oshoquotes',
'The real question is not whether life exists after death. The real question is whether you are alive before death. ~Osho #oshoquotes',
'They say: Think twice before you jump. I say: Jump first and then think as much as you want! ~Osho #oshoquotes',
'Nobody has the power to take two steps together; you can take only one step at a time ~Osho #oshoquotes',
'If you are a parent, open doors to unknown directions to the child so he can explore. Don\'t make him afraid of the unknown,give him support ~Osho #oshoquotes',
'Nobody is superior, nobody is inferior, but nobody is equal either. People are simply unique, incomparable. You are you, I am I. I have to contribute my potential to life; you have to contribute your potential to life. I have to discover my own being; you have to discover your own being. ~Osho #oshoquotes',
'Whatever you feel, you become. It is your responsibility. ~Osho #oshoquotes',
'Your whole idea about yourself is borrowed--  borrowed from those who have no idea of who they are themselves ~Osho #oshoquotes',
'To avoid pain, they avoid pleasure. To avoid death, they avoid life. ~Osho #oshoquotes',
'Always remember to judge everything by your inner feeling of bliss. ~Osho #oshoquotes',
'You exist in time, but you belong to  eternity- You are a penetration of eternity into the world of time-You are  deathless, living in a body of death- Your consciousness knows no death, no birth ~Osho #oshoquotes',
'A certain darkness is needed to see the stars. ~Osho #oshoquotes',
'I live my life based on 2 principles. One, I live as if today was my last day on earth. Two, I live today as if I am going to live forever. ~Osho #oshoquotes',
'Find ecstasy within yourself. It is not out there. It is in your innermost flowering. The one you are looking for is you. ~Osho #oshoquotes',
'In love the other is important; in lust you are important  ~Osho #oshoquotes',
'Be less of a judge and you will be surprised that when you become a witness and you don\'t judge yourself, you stop judging others too. And that makes you more human, more compassionate, more understanding.~Osho #oshoquotes',
'When I say be creative I don\'t mean that you should all go and become great painters and great poets. I simply mean let your life be a painting, let your life be a poem. ~Osho #oshoquotes',
'A little foolishness, enough 2 enjoy life, & a little wisdom to avoid the errors, that will do ~Osho #oshoquotes',
'One just needs a little alertness to see and find out: Life is really a great cosmic laughter. ~Osho #oshoquotes',
'All that is great cannot be possessed - and that is one of the most foolish things man goes on doing. We want to possess. ~Osho #oshoquotes',
'It\'s not a question of learning much.On the contrary.It\'s a question of UNLEARNING much.~Osho #oshoquotes',
'Love is the goal, life is the journey. ~Osho #oshoquotes',
'Love is not a relationship, love is a state of being; it has nothing to do with anybody else. One is not "in love", one is love. And of course when one is love, one is in love – but that is an outcome, a by-product, that is not the source. The source is that one is love.~Osho #oshoquotes',
'There is no need of any competition with anybody. you are yourself, and as you are, you are perfectly good. Accept yourself ~Osho #oshoquotes',
'It is beautiful to be alone, it is also beautiful to to be in love, to be with people. And they are complementary, not contradictory. ~Osho #oshoquotes',
'There exists no God. What exists is godliness, and that godliness surrounds you. We are all in the same ocean. ~Osho #oshoquotes',
'All the buddhas of all the ages have been telling you a very simple fact: Be — don´t try to become. Within these two words, be and becoming, your whole life is contained. Being is enlightenment, becoming is ignorance. ~Osho #oshoquotes',
'f you can bring your consciousness, your awareness, your intelligence to the act, if you can be spontaneous, then there is no need for any other religion, life itself will be the religion. ~Osho #oshoquotes',
'It is a strange thing ,that every child is born with a closed hand , and every body dies with an open hand ! ~Osho #oshoquotes',
'What is discipline? Discipline means creating an order within you. As you are, you are a chaos ~Osho #oshoquotes',
'You will find meaning in life only if you create it.It is a poetry to be composed. It is a song to be sung.It is a dance to be danced.~Osho #oshoquotes',
'No thought, no mind, no choice — just being silent, rooted in yourself. ~Osho #oshoquotes',
'You don\'t want to loose your old friend - the misery - You have invested too much into false - Hence the fear to be exposed -to be true - to be naked as you are ~Osho #oshoquotes',
'Sex has become more and more attractive because of its condemnation by priests ~Osho #oshoquotes',
'A man who is 100% sane is dead ~Osho #oshoquotes',
'In the space of no-mind, truth descends like light ~Osho #oshoquotes',
'The Truth Is That Existence Wants Your Life To Become A Festival Because When You Are Unhappy, You Also Throw Unhappiness All Around. ~Osho #oshoquotes',
'Lovers never surrender to each other, lovers simply surrender to love ~Osho #oshoquotes',
'The Real Self is dangerous: dangerous to the established church, dangerous to the state, dangerous to the crowd, dangerous to tradition, because once a man knows his real self, he becomes an individual ~Osho #oshoquotes',
'There is great difference between trust and belief. Trust is personal, Belief is social. ~Osho #oshoquotes',
'you need power only to do something harmful.otherwise love is enough,compassion is enough ~Osho #oshoquotes',
'Go inwards. Find your inner space, and suddenly, you will find an explosion of light, of beauty, of ecstasy -as if suddenly thousands of roses have blossomed within you and you are full of their fragrance. ~Osho #oshoquotes',
'The tongue never slips – remember this always. What goes on within the mind comes invariably on the tongue. ~Osho #oshoquotes',
'My whole teaching consists of two words, meditation and love. Meditate so that you can feel immense silence, and love so that your life can become a song, a dance, a celebration.  ~Osho #oshoquotes',
'In Buddhist terminology there is nothing like sin, only mistakes, errors. There is no condemnation. You can correct the error, you can correct the mistake. It is simple.  ~Osho #oshoquotes',
'Be ordinary, but bring a quality of awareness to your ordinary life. Bring God to your ordinary life introduce God into your ordinary life. Sleep, eat, love, pray, meditate, but don’t think that you are making or doing something special—and then you will be special. ~Osho #oshoquotes',
'Intelligence comes from meditation, intelligence comes from rebellion, intelligence does not come from memory ~Osho #oshoquotes',
'If you live consciously, if you try to bring consciousness to every act that you go through, you will be living in a silent, blissful state, in serenity, in joy, in love. Your life will have the flavour of a festival. ~Osho #oshoquotes',
'You don’t have any problems — only this much has to be understood. This very moment you can drop all problems. because they are your creations.  ~Osho #oshoquotes',
'Wherever you are afraid, try to explore, and you will find death hiding somewhere behind. All fear is of death. Death is the only fear source. ~Osho #oshoquotes',
'Remain in wonder if you want the mysteries to open up for you. Mysteries never open up for those who go on questioning. Questioners sooner or later end up in a library. Questioners sooner or later end up with scriptures, because scriptures are full of answers. And answers are dangerous, they kill your wonder.~Osho #oshoquotes',
'Enlightenment will be now the beginning, not the end. Beginning of a non-ending process in all dimensions of richness. ~Osho #oshoquotes',
'Love is the opposite of [lust]: respecting the other as an end unto himself or herself. When you love someone as an end unto himself, then there is no feeling of hurt; you become enriched through it. Love makes everybody rich. ~Osho #oshoquotes',
'Crowds create illusions. ~Osho #oshoquotes',
'Tomorrow never comes, it is always today. ~Osho #oshoquotes',
'Don\'t seek, don\'t search, don\'t ask, don\'t knock, don\'t demand ~ relax. If you relax it comes, if you relax it is there. If you relax, you start vibrating with it. ~Osho #oshoquotes',
'The greatest fear in the world is of the opinions of others. And the moment you are unafraid of the crowd you are no longer a sheep, you become a lion. A great roar arises in your heart, the roar of freedom ~Osho #oshoquotes',
'Meditation is a surrender, it is not a demand. It is not forcing existence your way, it is relaxing into the way existence wants you to be. It is a let-go.~Osho #oshoquotes',
'Never belong to a crowd; Never belong to a nation; Never belong to a religion; Never belong to a race. Belong to the whole existence. Why limit yourself to small things? When the whole is available.” ~Osho #oshoquotes',
'Commit as many mistakes as possible, remembering only one thing: don’t commit the same mistake again. And you will be growing. ~Osho #oshoquotes',
'A man becomes a Buddha the moment he accepts all that life brings with gratitude. ~Osho #oshoquotes',
'Life is not a problem. To look at it as a problem is to take a wrong step. It is a mystery to be lived, loved, experienced. ~Osho #oshoquotes',
'There is no one lonelier than God! ~Osho #oshoquotes',
'Only laughter makes a man rich, but the laughter has to be blissful. ~Osho #oshoquotes',
'You should live in the world but remain untouched by it. You should remain in the world, but the world should not remain in you. ~Osho #oshoquotes',
'This is the secret, THE secret ... De-automatize ~Osho #oshoquotes',
'When somebody comes with a conclusion, then he looks through that conclusion and chooses only things which support his position. ~Osho #oshoquotes',
'Logic is a prostitute It can help anybody - for or against, it has no problem.~Osho #oshoquotes',
'Love is wild; its whole beauty is in its wildness. It comes like a breeze with great fragrance, fills your heart, and suddenly where there was a desert there is a garden full of flowers. ~Osho #oshoquotes',
'People think that those who commit suicide are against life—they are not. They are too lusty for life, they have great lust for life; and because life is not fulfilling their lust, in anger, in despair, they destroy themselves.~Osho #oshoquotes',
'People sometimes ask me , what religion are you ? i always answer by saying, ''i am a little part of all religions and and a big part of no religion ~Osho #oshoquotes',
'Joy is spiritual. It is different, totally different from pleasure or happiness. It has nothing to do with the outside, with the other, it is an inner phenomenon. ~Osho #oshoquotes',
'Never interfere in anybody´s life and don´t allow anybody to interfere in your life. ~Osho #oshoquotes',
'respect life,revere life.there is nothing more holy than life,nothing more divine than life. ~Osho #oshoquotes',
'When you love, love as if the person is a god, not less than that. Never love a woman as a woman and never love a man as a man ~Osho #oshoquotes',
'Mind: A beautiful servant, a dangerous master. ~Osho #oshoquotes',
'God is a person; godliness is a quality. You cannot become God, but you can be godly. ~Osho #oshoquotes',
'Think before you desire a thing. There is every possibility that it will be fulfilled, and then you will suffer. ~Osho #oshoquotes',
'Love a woman as a goddess, then love becomes worship. ~Osho #oshoquotes',
'Help the world to become better. Don\'t leave the world just the same as you have found it - make it a little better, make it a little more beautiful. ~Osho #oshoquotes',
'If you can grow in love, you will grow in awareness. If you grow in awareness, you will grow in love ~Osho #oshoquotes',
'Courage is a love affair with the unknown. ~Osho #oshoquotes',
'There is no sorrow except in captivity. ~Osho #oshoquotes',
'One who ”knows,” knows there is no need to discourse; knowing is enough ~Osho #oshoquotes',
'Remain in the world, act in the world, do whatsoever is needful, and yet remain transcendental, aloof, detached, a lotus flower in the pond. ~Osho #oshoquotes',
'Knowledge always liberates. ~Osho #oshoquotes',
'Tension means you want to be something else which you are not. ~Osho #oshoquotes',
'No, explanation is not needed – only exclamation, a wondering heart, awakened, surprised, feeling the mystery of life each moment. Then, and only then, you know what truth is. And truth liberate ~Osho #oshoquotes',
'Love is a spiritual phenomenon; lust is physical. Ego is psychological; love is spiritual. ~Osho #oshoquotes',
'Buddha is a Buddha, a Krishna is a Krishna, and you are you. And you are not in any way less than anybody else. Respect yourself, respect your own inner voice and follow it. ~Osho #oshoquotes',
'A respectable person is invariably unrespectable within. ~Osho #oshoquotes',
'Be-don\'t try to become.~Osho #oshoquotes',
'All our attachments are outward oriented and hence this illusion. ~Osho #oshoquotes',
'Life in itself has no meaning. Life is an opportunity to create meaning. ~Osho #oshoquotes',
'Go into your mind, analyze your mind. Somewhere you have tricked yourself. ~Osho #oshoquotes',
'If you are not selfish you will not be altruistic, remember ~Osho #oshoquotes',
'Love is the true God—not the God of theologians, but the God of Buddha, Jesus, Mohammed, the God of the Sufis. ~Osho #oshoquotes',
'Nothing is good. Nothing is bad. When this dawns in your consciousness, suddenly you are together,all fragments have disappeared into one unity.  ~Osho #oshoquotes',
'Be a lotus flower. Be in the water, and do not let the water touch you. ~Osho #oshoquotes',
'Love the person, but give the person total freedom. Love the person, but from the very beginning make it clear that you are not selling your freedom. ~Osho #oshoquotes',
'People sometimes ask me , what religion are you ? I always answer by saying, ''Iam a little part of all religions and and a big part of no religion. ~Osho #oshoquotes',
'All that you call sin is nothing but mistakes. And mistakes are the way of learning. Those people who never commit mistakes are the most stupid people ~Osho #oshoquotes',
'The mind always moves on and on. Whatsoever you get becomes useless. The moment you get it, it is useless. This is desire. Buddha has called it trishna: this is becoming. ~Osho #oshoquotes',
'Include and grow. Include and expand. ~Osho #oshoquotes',
'The world is nothing but your own magnified mind ~Osho #oshoquotes',
'There is only a difference of proportion of madness between an average man and a mad man; the quality of madness is the same. ~Osho #oshoquotes',
'Even if they can find a lover they demand perfection, and the love is destroyed because of that demand. ~Osho #oshoquotes',
'Whenever a situation arises that creates fear, there are two alternatives—either you fight or you take flight. ~Osho #oshoquotes',
'The small flower is as total as the sun. ~Osho #oshoquotes',
'Darkness is an absence of light. Ego is an absence of awareness. ~Osho #oshoquotes',
'Meditation is nothing but enjoying your beautiful aloneness. Celebrating yourself; that’s what meditation is all about ~Osho #oshoquotes',
'Whatever is of consequence in life, is always hidden from view. What is manifest is the outer cover; what remains unmanifest is the soul within. ~Osho #oshoquotes',
'The East has failed because it tried meditation without love. The West has failed because it tried love without meditation. My whole effort is to give you a synthesis, the whole—which means meditation plus love. ~Osho #oshoquotes',
'To covet beatitude is also avarice. ~Osho #oshoquotes',
'Real meditation means: don’t avoid the inner madhouse; enter into it, face it, encounter it, be watchful, because it is through watchfulness that you will overcome it. ~Osho #oshoquotes',
'The family is one of the greatest traps that society has used for millennia to keep man a slave ~Osho #oshoquotes',
'Don’t allow your life to become just a dead ritual. Let there be moments, unexplainable. ~Osho #oshoquotes',
'The ordinary love is a demand, the real love is a sharing. It knows nothing of demand; it knows the joy of giving. ~Osho #oshoquotes',
'When somebody on the outside fits with your inner image, you fall in love -- that is the meaning of love. ~Osho #oshoquotes',
'Real love is considerate but has no concern. ~Osho #oshoquotes',
'And if you have loved a man or a woman, you will want to give the other person as much freedom as possible. If love cannot give freedom, then it is not love. ~Osho #oshoquotes',
'God has created you because he loved you. He loved you so much that he could not resist the temptation to create you.  ~Osho #oshoquotes',
'There is no greater luxury than meditation. Meditation is the last luxury, because it is the ultimate love affair. ~Osho #oshoquotes',
'Creativity is the fragrance of individual freedom. ~Osho #oshoquotes',
'The ultimate mysteries are opened only to those who have immense patience ~Osho #oshoquotes',
'A creative person is one who has insight, who can see things nobody else has ever seen before, who hears things that nobody has heard before—then there is creativity. ~Osho #oshoquotes',
'I live in my own way, I don’t consider you. I don’t consider anybody at all—because if you start considering others you can’t live your life authentically. Consider and you will become phony ~Osho #oshoquotes',
'If you go to a tree and start talking, or to a flower, a rose, people will think you are mad. If you go to the church and talk to the cross or to an image, nobody will think you are mad, they will think you are religious. ~Osho #oshoquotes',
'Dance while you are alive. Breathe blissfully while you are alive. Sing while you are alive. Love, meditate while you are alive. ~Osho #oshoquotes',
'truth cannot be found by intellectual effort because truth is not a theory, it is an experience ~Osho #oshoquotes',
'Meaning is man-created. And because you constantly look for meaning, you start to feel meaninglessness ~Osho #oshoquotes',
'There is far more opportunity than there is ability. ~Osho #oshoquotes',
'It is not a question of money, power, and prestige; it is a question of what intrinsically you want to do. Do it, irrespective of the results, and your boredom will disappear. ~Osho #oshoquotes',
'Dreams have to be made real, not reality changed into dreams. ~Osho #oshoquotes',
'Why should one be a Christian? It is ugly. Be a christ if you can be, but don’t be a Christian. Be a buddha if you have any respect for yourself, but don’t be a Buddhist. The Buddhist believes. Buddha knows. ~Osho #oshoquotes',
'One thing is certain: Existence is overflowing. With everything it is luxurious. It is not a poor existence, no. Poverty is man’s creation. ~Osho #oshoquotes',
'If you are intelligent, if you are alert, the ordinary becomes the extraordinary. ~Osho #oshoquotes',
'Misery is an indication that you are in conflict. ~Osho #oshoquotes',
'The only way to go beyond death is to accept death. Then it disappears. The only way to be fearless is to accept fear. Then the energy is released and becomes freedom. ~Osho #oshoquotes',
'Love is the ecstasy when the walls between two people crumble down, when two lives meet, when two lives unite. ~Osho #oshoquotes',
'Zen is the purest of meditations: just sit silently, doing nothing. ~Osho #oshoquotes',
'Your Mind is a Garden,Your Thoughts are the Seeds. You can grow Flowers or weeds...~Osho #oshoquotes',
'Express your uniqueness in whatsoever you do. Express your individuality. Let existence be proud of you. Life will not be felt like a drag; it will become a fragrance.”~Osho #oshoquotes',
'Sing your song, and if nobody listens, sing it alone and enjoy it. ~Osho #oshoquotes',
'Zen gives you tremendous dignity. There is no authority anywhere. Freedom is utter and ultimate. ~Osho #oshoquotes',
'The moment you start seeing life as non-serious, a playfulness, all the burden on your heart disappears.All the fear of death, of life, of love - everything disappears.  ~Osho #oshoquotes',
'Spontaneousness is thought to be madness. Formalities are thought to be sanity. Just the opposite is the reality. ~Osho #oshoquotes',
'No meditation, no life. Know meditation, know life. ',
'Creators almost always go mad. ~Osho #oshoquotes',
'Live as intensely as possible, burn your candle of life from both ends. ~Osho #oshoquotes',
'Millions of beauties and splendors are waiting for you. You go on moving around and around, never entering into the temple of life. The door is the heart. ~Osho #oshoquotes',
'Don’t be an interpreter of reality, be a visionary. Don’t think about it, see it! ~Osho #oshoquotes',
'Remember, a person who cannot be angry cannot be loving. The roses grow only with the thorns ~Osho #oshoquotes',
'Nothing in life is ever wasted, especially steps taken towards truth. ~Osho #oshoquotes',
'Existence already accepts you—that’s why you are here. Otherwise you would not be. This is my basic teaching to you. Existence already accepts you. You do not have to earn it, you are already worthy.  ~Osho #oshoquotes',
'Millions of people have lived on the earth, and we don’t know even their names. Accept that simple fact—you are here for only a few days and then you will be gone. These few days are not to be wasted in hypocrisy, in fear. These days have to be rejoiced. ~Osho #oshoquotes',
'Truth cannot be raided; it is attained through surrender, not through struggle. It is conquered through total surrender. ~Osho #oshoquotes',
'Do anything totally and it is finished; you will not carry a psychological memory of it. Do anything incompletely and it hangs with you. ~Osho #oshoquotes',
'The past is memory, the future is imagination. Only the present is time. The past is not, it has already gone. The future is not; it has not come yet. Only the present is.  ~Osho #oshoquotes',
'Training is needed, but training is not the goal. Training is just a means. ~Osho #oshoquotes',
'Life i s not a problem to be solved, it\'s a mystery to be lived.~Osho #oshoquotes',
'Once you have heard the Indian Bamboo flute then everything else is just ordinary! ~Osho #oshoquotes',
'If one is not a meditator, howsoever good one is it is all useless. ~Osho #oshoquotes',
'When the new knocks on your door, open it! ~Osho #oshoquotes',
'This is the answer: live moment to moment and you become a buddha.~Osho #oshoquotes',
'weakness is not a transformation; again it is a deception. ~Osho #oshoquotes',
'Teaching comes through the head, learning happens through the heart. ~Osho #oshoquotes',
'To be "great" is an ego goal; to be real is existential. ~Osho #oshoquotes',
'What matters is that you should remain exactly what you are because from there starts growth. ~Osho #oshoquotes',
'Freedom to dream has not yet been taken away by governments. ~Osho #oshoquotes',
'The only thing in your hands is your life—make it as rich as possible. ~Osho #oshoquotes',
'Life is a pilgrimage, and unless love is attained, it remains a pilgrimage, never reaching anywhere. ~Osho #oshoquotes',
'you cannot cling to anything in a changing world. ~Osho #oshoquotes',
'It is not the truth which has to be sought, it is you who have to be brought home. ~Osho #oshoquotes',
'Truth cannot be decided by the vote of the majority because truth is utterly individual and private. ~Osho #oshoquotes',
'It is others’ opinion about you that creates the ego. ~Osho #oshoquotes',
'Remember, truth cannot be conquered. One has to surrender to truth, one has to be conquered by truth. ~Osho #oshoquotes',
'Life can become a celebration if you know how to live without concern. Otherwise life becomes a long prolonged disease, an illness which culminates only in death. ~Osho #oshoquotes',
'The true prayer is only of thankfulness; just a simple thank you is enough. ~Osho #oshoquotes',
'Security is of the world, insecurity is of the divine ~Osho #oshoquotes',
'All lovers are in trouble. The trouble is not personal; it is in the very nature of things. They would not have been ~Osho #oshoquotes',
'People behave as if they were blind and deaf. This is the cunning mind which goes on saying: Don’t go in this direction – there is danger. ~Osho #oshoquotes',
'Law is for those who have forgotten the language of the heart and only know the language of the mind. ~Osho #oshoquotes',
'This is the Zen approach: nothing is there to be done. There is nothing to do. One has just to be. Have a rest, and be ordinary and be natural.  ~Osho #oshoquotes',
'It is not that you fall in love with a beautiful person; the process is just the opposite. When you fall in love with some person, the person looks beautiful. ~Osho #oshoquotes',
'Everybody is born creative, but very few people remain creative. ~Osho #oshoquotes',
'Remember, it is ultimately your mind which makes anything attractive or unattractive. It is you who is the deciding factor. ~Osho #oshoquotes',
'A morality that comes with effort is immoral. A morality that comes without effort is the only morality there is. ~Osho #oshoquotes',
'He believes in the unity of the opposites. And that is how life is. ~Osho #oshoquotes',
'What is enlightenment?—the capacity to see oneself as one really is. ~Osho #oshoquotes',
'Any love that is followed by jealousy is certainly not true love, it is biological instinct. ~Osho #oshoquotes',
'I would like Epicurus and Buddha to become one. ~Osho #oshoquotes',
'Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for. ~Epicurus',
'Death is nothing to us, since when we are, death has not come, and when death has come, we are not. ~Epicurus~Osho #oshoquotes',
'Not what we have But what we enjoy, constitutes our abundance. ~Epicurus',
'And remember, the very idea of getting free is again an ideal. Freedom is not an ideal, it is a by-product of accepting whosoever you are. ~Osho #oshoquotes',
'You never suffer nearly as much as you imagine you suffer. You never suffer the illnesses you most dread nor the miseries that you fear. ~Osho #oshoquotes',
'And remember, the very idea of getting free is again an ideal. Freedom is not an ideal, it is a by-product of accepting whosoever you are. ~Osho #oshoquotes',
'You never suffer nearly as much as you imagine you suffer. You never suffer the illnesses you most dread nor the miseries that you fear. ~Osho #oshoquotes',
'Everybody is ignorant, only on different subjects. ~Osho #oshoquotes',
'Just as trees need roots in the earth, man is also a tree and needs roots in existence or else he will live a very unintelligent life. ~Osho #oshoquotes',
'Love is the key, love is the secret. ~Osho #oshoquotes',
'Truth has nothing to do with your belief! Whether you believe or not makes no difference to truth.  ~Osho #oshoquotes',
'Be a man: accept the challenge of the unknown, of the beyond. Let it become a great dream in your being. ~Osho #oshoquotes',
'This is the secret of the golden flower: if the heart can die the flower will bloom, die as you are so you can be reborn. ~Osho #oshoquotes',
'He has to fight but with no anger. This seems difficult, because you even love with anger, yet he has to fight without anger. ~Osho #oshoquotes',
'All your troubles are caused by your head; your thoughts, your reasoning, your arguing, your obsessing and wondering. ~Osho #oshoquotes',
'And the greatest adventure is not going to the moon - the greatest adventure is going to your own innermost core. ~Osho #oshoquotes',
'Don’t judge, because the moment you start judging you will forget watching. ~Osho #oshoquotes',
'Act,speak with full awareness and then you will find a tremendous change in you. The very fact that you are aware changes your acts. ~Osho #oshoquotes',
'Accept whatsoever you are. In that very acceptance you will accept others, too. ~Osho #oshoquotes',
'That is the difference between a botanist and a poet: a botanist knows about the flower, the poet knows the flower. ~Osho #oshoquotes',
'But it happens many times that stupid people have beautiful memories, and intelligent people are not so good as far as memory is concerned. ~Osho #oshoquotes',
'So learn one thing, that to expect is bad and that the world is not here to fulfill your expectations. ~Osho #oshoquotes',
'Always be alert, never get hooked into anything negative. Many people go on studying negative things; their energies are simply wasted. There is no art of dying. Or, the art of living is the art of dying. Live! ~Osho #oshoquotes',
'Love is a very basic need... as basic as food. Without food and without love, you will start shrinking. Without food, the body will start dying. Without love, your innermost being starts dying ~Osho #oshoquotes','~Osho #oshoquotes',
'You need moralities, precepts, principles, Bibles, Korans, Gitas to direct you because you are not confident in the inner force. ~Osho #oshoquotes',
'What is the concern? It is about how others are impressed by you. But why are you so worried about others, so worried that you cannot live at all? ~Osho #oshoquotes',
'Eat like an emperor. That does not depend on the quality of the food, it depends on the eater, the way he celebrates it. ~Osho #oshoquotes',
'Love is not a beggar. It never says, “Give me love.” Love is always an emperor, it only knows to give. ~Osho #oshoquotes',
'There is no other space, no other time. This moment is all. In this moment the whole existence converges, in this moment all is available. ~Osho #oshoquotes',
'Zen is magic. It gives you the key to open the miraculous. And the miraculous is in you and the key is also in you. ~Osho #oshoquotes',
'Flow unconditionally with the unconscious wherever it leads. ~Osho #oshoquotes',
'The proverb that says that the empty mind is the devil’s workshop is just nonsense. Just the opposite is the truth: the occupied mind is the devil’s workshop! ~Osho #oshoquotes',
'To err is human, to admit it is divine. It is absolutely human to commit mistakes. To admit, without any guilt—you are simply admitting your humanity by admitting your mistakes—brings a transformation in your being. Something of the divine, something of the beyond starts opening up. ~Osho #oshoquotes',
'When you are so wrapped up in seeking pleasure you cannot love, because the person who seeks pleasure uses the other as a means. ~Osho #oshoquotes',
'Sometimes a smile, a giggle can say more than words do; words are not that articulate. And if you use words where a smile is enough you will only spoil the game. ~Osho #oshoquotes',
'When energy turns in—what Buddha calls paravritti, the coming back of your energy to the source—suddenly clarity is attained. Then you can see clouds a thousand miles away, and then you can hear ancient music in the pines. ~Osho #oshoquotes',
'Life is not a static phenomenon. It is a flux, a riverlike flux; it needs constant change. It needs moment-to-moment awareness; otherwise you will be left behind. ~Osho #oshoquotes',
'You cannot step in the same river twice,” because it is always flowing ~Osho #oshoquotes',
'Truth is an experiencing, not an experience. It is a knowing, not knowledge. ~Osho #oshoquotes',
'Yoga is a method to come to a nondreaming mind. Yoga is the science to be in the here and now.  ~Osho #oshoquotes',
'The mystery is solved when you have become the mystery itself. ~Osho #oshoquotes',
'The crowd is blind. And to have eyes in this crowd is to be condemned, is to be crucified. ~Osho #oshoquotes',
'The man of understanding, meditation, is not a man of control—just the opposite. He is a watcher. And if you want to watch, you have to be absolutely nonjudgmental ~Osho #oshoquotes',
'The path of Tao is not that of sudden enlightenment. It is not like Zen. Zen is sudden enlightenment, Tao is gradual growth. ~Osho #oshoquotes',
'The day is not only God\'s, the night is his also. ~Osho #oshoquotes',
'God is the name given by theologians to something they know nothing about. There is no God; the whole existence is made of the stuff called love. ~Osho #oshoquotes',
'Everything you show to the other is not the real but the desired, not that which is but that which should be. ~Osho #oshoquotes',
'In the world of matter nothing succeeds like the ego, in the world of consciousness nothing fails like the ego. ~Osho #oshoquotes',
'I HAVE TOLD you that a woman is to be loved, not understood. ~Osho #oshoquotes',
'Only foolish people believe. A man of understanding has faith not belief. Faith is different. Faith means trusting life, trusting it so absolutely that one is ready to go with it anywhere. ~Osho #oshoquotes',
'Because if you are serious, they think you\'re valuable; if you go on laughing and you make your life fun, they think you\'re a fool. ~Osho #oshoquotes',
'Taoists don’t have any maps. ~Osho #oshoquotes',
'A Taoist is a man who does only that which is absolutely necessary. His life is almost like a telegram. ~Osho #oshoquotes',
'Let the goal of the whole be your goal. Don\'t seek any private goal. Just be a part, and an infinite beauty and grace happens. ~Osho #oshoquotes',
'Life is nothing but an opportunity for love to blossom. ~Osho #oshoquotes',
'The idea of a separate center is the root of the ego. ~Osho #oshoquotes',
'India cannot be India again until temples become alive again ~Osho #oshoquotes',
'The one you are looking for is you. ~Osho #oshoquotes',
'If the gold wants to be purified, it has to pass through fire.  ~Osho #oshoquotes',
'love creates a great need to be alone, and aloneness creates a great need to be together. ~Osho #oshoquotes',
'nothing that is small; it all depends on you, what you make out of it. ~Osho #oshoquotes',
' These things are more important than any medicine. When you are sick, call a doctor. But more important, call those who love you because there is no medicine more important than love.~Osho #oshoquotes',
'Buddhas also have to be swept away, because the door can become a hindrance if you cling to it. ~Osho #oshoquotes',
'A thief thinks everybody is a thief and a sage thinks everybody is a sage. It all depends on you: if you become God the whole existence becomes godly. ~Osho #oshoquotes',
'The way of the heart is beautiful but dangerous. The way of the mind is ordinary but safe.  ~Osho #oshoquotes',
'Watch the thoughts, because in your watching them, they disappear. Then watch your emotions, sentimentalities; by your watching, they also disappear. Then your heart is as innocent as that of a child, and your head is as great a genius as Albert Einstein, Bertrand Russell, Aristotle ~Osho #oshoquotes',
'No, being concerned is not good, because if you are concerned too much, you will become tense. And if you become tense you cannot help.~Osho #oshoquotes',
'Remember one thing. That you should not leave the Earth until you have made it a little more beautiful. A little lovelier. A little more loving. ~Osho #oshoquotes',
'Reason is an effort to know the unknown and intuition is the happening of the unknowable. To penetrate the unknowable is possible, but to explain it is not. The feeling is possible, the explanation is not. ~Osho #oshoquotes',
'Cultivation means you will be creating something around yourself which you are not. ~Osho #oshoquotes',
'All these things are part of it: let-go, trust, surrender, love, acceptance, going with the flow, union with existence, egolessness, ecstasy. All these are part of it, and all these start happening if you learn the ways of relaxation. ~Osho #oshoquotes',
'Consciousness is yours. Conscience is given by the society. ~Osho #oshoquotes',
'The day you leave, this will be your only contentment: if you have made the existence a little more beautiful ~Osho #oshoquotes',
'It is only through silence that truth can be said, because it is only through silence that the truth is heard. ~Osho #oshoquotes',
'If they say you are good, you have to follow their rules to remain good. ~Osho #oshoquotes',
'So if you want to prove something, it shows that you are doubtful about it. You want to destroy your doubt through other\'s eyes, through their opinions. ~Osho #oshoquotes',
'The politician is the poorest man in the world, the most empty man, the most hollow—stuffed with straw and nothing else. ~Osho #oshoquotes',
'Drop desiring and bliss will be yours. ~Osho #oshoquotes',
'Dance madly as if all of life is meant for dancing and celebrating. ~Osho #oshoquotes',
'Spontaneity is the fragrance of no-mind. ~Osho #oshoquotes',
'I say to you that suffering is not holding onto you, you are holding onto suffering. ~Osho #oshoquotes',
'A man is never an individual unless he is possessed by a desire so deep that it is deeper than life, so deep that he is ready to sacrifice his life for it. ~Osho #oshoquotes',
'If all your questions can be taken away, your ignorance is bound to disappear, and what remains is innocence. And innocence is a light unto itself ~Osho #oshoquotes',
' Meditation is witnessing. To meditate means to become a witness. Meditation is not a technique at all!  ~Osho #oshoquotes',
'Comfort is an attitude of mind; it is an approach toward life. ~Osho #oshoquotes',
'Existence does not want carbon copies; it loves your uniqueness. ~Osho #oshoquotes',
'Be more meditative, become more conscious of your being. Let your inner world become more silent, and love will be flowing through you. ~Osho #oshoquotes',
'Remember, that which appeals to the ego cannot help your spiritual growth. ~Osho #oshoquotes',
'Enjoy this moment because it may not come again. ~Osho #oshoquotes',
'Nobody wants you to know that life is simply romance. And that is my crime—because that is my whole teaching, that life is nothing but romance. ~Osho #oshoquotes',
'If I cannot be loving alone, if I can be loving only with someone I love, then I am not really mature yet.  ~Osho #oshoquotes',
'There are a few things that you have to understand—I cannot give any proofs for them, they are beyond proofs. Only your experience will give you the proof. ~Osho #oshoquotes',
'You can never come to a moment when you can say, “Now I am certain.” When you say you are certain, you simply declare your death; you have committed suicide. ~Osho #oshoquotes',
'Acts don\'t mean anything. Acts do not matter--you,your awareness, your being conscious,mindful, is what matters. What you do is not the concern. ~Osho #oshoquotes',
'Truth... has no obligation to console you. ~Osho #oshoquotes',
'Fear is always about something in the future. Fear never exists in the present moment. ~Osho #oshoquotes',
'The first thing for you to understand about yourself is that you don\'t know anything.~Osho #oshoquotes',
'Politics corrupted science because its own interest was only war. ~Osho #oshoquotes',
'Only idiots are not controversial. ~Osho #oshoquotes'
'Today here and now, at the age of four, we eat from the tree of knowledge and have fallen from grace ~Osho #oshoquotes',
'Once you live according to the rules, you will suffer. You will suffer because you cannot love spontaneously, you cannot enjoy, you cannot dance, you cannot sing. ~Osho #oshoquotes',
'You cannot be angry when alone ~Osho #oshoquotes',
'Danger for the mind, of course, but not for you. ~Osho #oshoquotes',
'If you say no to love, you are less than you were before ~Osho #oshoquotes',
'You all know watching, so there is no question of learning it. It is just a question of changing the object of watching. ~Osho #oshoquotes',
'The trouble lies deeper, deeper than your mind, and you have to go deep within yourself. ~Osho #oshoquotes',
'Sex is animal, love is human, compassion is divine. Sex is physical, love is psychological, compassion is spiritual. ~Osho #oshoquotes',
'Mind is basically the beginning of madness. And if you are too much in it, it will drive you mad~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
    '~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
    '~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
    '~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
    '~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
'~Osho #oshoquotes',
    '~Osho #oshoquotes',

]
#
# new_list = [Quotes_list[i] for i in range(len(Quotes_list))]
#
# for i in range(len(new_list)):
#     print(new_list[i],"\n")

















