Quotes_list=[
'Confidence and stupidity are a very dangerous combination, but they generally go together. @SadhguruJV #SadhguruQuotes',
'Death is a fiction created by people who live their lives in total unawareness. There is only life, life and life alone, moving from one dimension to another, another dimension to another. @SadhguruJV #SadhguruQuotes',
'When you have that, you dream of this and when you have this, you dream of that. Maybe you call it romantic, but it’s just plain stupidity. It destroys life. @SadhguruJV #SadhguruQuotes',
'It is our compulsive reaction to the situations in which we are placed that causes stress. @SadhguruJV #SadhguruQuotes',
'The only thing that stands between you and your well-being is a simple fact: you have allowed your thoughts and emotions to take instruction from the outside rather than the inside.@SadhguruJV #SadhguruQuotes',
'To rise above the modifications of your mind, when you cease your mind, when you cease to be a part of your mind, that is yoga. @SadhguruJV #SadhguruQuotes',
'Your life is just about craving, and making something else tremendously more important than you. @SadhguruJV #SadhguruQuotes',
'To program the calories you must consume and the number of hours you must sleep is a foolish way to handle life. @SadhguruJV #SadhguruQuotes',
'Confusion is a good state to be in. It means you are looking, constantly looking.  @SadhguruJV #SadhguruQuotes',
'The man who does only as much as is needed will only get that much. @SadhguruJV #SadhguruQuotes',
'Generally, the smartest people on the planet – those people who think they are really smart – tend to have the most horrible relationships. @SadhguruJV #SadhguruQuotes',
'Yogis are not against pleasure. It is just that they are unwilling to settle for little pleasures. They are greedy. @SadhguruJV #SadhguruQuotes',
'Money is definitely needed, but how much money do we really need? If we would change our idea of a successful life to a joyful life, we would find our need for money would dramatically decrease. @SadhguruJV #SadhguruQuotes',
'The way you eat not only decides your physical health, but the very way you think, feel, and experience life. Trying to eat intelligently means understanding what kind of fuel this body is designed for and accordingly supplying it, so that it functions at its best. @SadhguruJV #SadhguruQuotes',
'To be enlightened is not a condition of certainty. It is to move from limited knowing to boundless unknowing, from gravitas to grace. @SadhguruJV #SadhguruQuotes',
'The most incredible thing is that you can know everything you wish to know with your eyes closed. @SadhguruJV #SadhguruQuotes',
'Most carnivorous animals do not eat every day—definitely not three times a day! They know the food they eat moves very slowly through their tracts. @SadhguruJV #SadhguruQuotes',
'Mysticism is like pure science; it has no use. Mysticism is just the human longing to know… Occult is not science. Occult is just technology. @SadhguruJV #SadhguruQuotes',
'You cannot choose a Guru. Deepen your longing and the Guru will choose you. @SadhguruJV #SadhguruQuotes',
'Only if you know to what extent your logic should go and where it should not go, your life will be beautiful. @SadhguruJV #SadhguruQuotes',
'One should use information and logic as a drunkard would use a lamp post, only for support, not for illumination. @SadhguruJV #SadhguruQuotes',
'Your body is on loan from the planet. All the countless numbers of people who have lived on this planet before you and me have all become topsoil, and so will you. This planet will collect back atom by atom what it has loaned to you. @SadhguruJV #SadhguruQuotes',
'Responsibility simply means your ability to respond. @SadhguruJV #SadhguruQuotes',
'There is only one calamity: ignorance. And there is only one solution: enlightenment. @SadhguruJV #SadhguruQuotes',
'Unless you do the right things, the right things will not happen to you. @SadhguruJV #SadhguruQuotes',
'But when it comes to the inner situation, there is only one ingredient: you. At least you must happen the way you want. @SadhguruJV #SadhguruQuotes',
'If you handle your entire life with logic alone, you will end up a mess. @SadhguruJV #SadhguruQuotes',
'Why do we refer to the mind as a circus? A circus is not a mess; a circus is a very coordinated activity deliberately made to look like a mess. On one level it is a mess, but on another, it is a highly coordinated activity.@SadhguruJV #SadhguruQuotes',
'Your ideas of good and bad are just a certain level of prejudice against life. @SadhguruJV #SadhguruQuotes',
'Man needs entertainment simply to hide his madness. If he was perfectly sane, he would not need entertainment. He could just sit and watch this bamboo grow. He does not really need entertainment. @SadhguruJV #SadhguruQuotes',
'Whatever has been the highest experience in your life should become the centerpiece around which your life is structured. @SadhguruJV #SadhguruQuotes',
'An intellectual understanding that is not backed by experiential knowledge can lead to mind games and deceptive states. @SadhguruJV #SadhguruQuotes',
'Renunciation, or refusing to identify with that which one gathers (however precious it may be), is the ultimate doorway to knowing. @SadhguruJV #SadhguruQuotes',
'If you want God as a tranquilizer, it is okay as an idea, but if you want the Divine to be an awakening process in your life, an idea is not good enough. @SadhguruJV #SadhguruQuotes',
'They have been promising us for a long time — in every culture — that they are going to take us to heaven. They promise heaven because they are making a hell out of this place. @SadhguruJV #SadhguruQuotes',
'The path is not difficult. It is very simple. If you are simple, it’s very simple. If you are all wound up, the path is very, very winding. That’s all it is. @SadhguruJV #SadhguruQuotes',
'I learned to create a little more space between my thoughts and actions—actually between my feelings and reactions. This is extremely important; without it, life can be a real roller coaster ride. @SadhguruJV #SadhguruQuotes',
'By consciously getting your body into a certain posture, you can also elevate your consciousness, you can change the very way you feel, think, understand, and experience life simply by sitting in a particular way. @SadhguruJV #SadhguruQuotes',
'Life is a circus when your intellect and your body alone are involved. Life is a dance, when the intelligence begins to play its role @SadhguruJV #SadhguruQuotes',
'Enlightenment is not an attainment or an achievement. It is a homecoming. @SadhguruJV #SadhguruQuotes',
'The identity around which the intellect functions is called ahankara. @SadhguruJV #SadhguruQuotes',
'Lovers don’t finally meet somewhere. They’re in each other all along. ~Rumi #rumiquotes',
]